//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PR17_restaurant__Kile.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int id { get; set; }
        public int naimenov { get; set; }
        public int stol { get; set; }
        public string kolichestvo { get; set; }
        public decimal cena { get; set; }
        public int status { get; set; }
    
        public virtual TableName TableName { get; set; }
        public virtual TableStatus TableStatus { get; set; }
        public virtual TableStol TableStol { get; set; }
    }
}
